"""
build_exe.py - bundle Flurry into a single-file flurry.exe via PyInstaller.

Run from the repo root:
    pip install pyinstaller
    python build_exe.py

Output: dist/flurry.exe (Windows) or dist/flurry (macOS/Linux).

The bundled binary is fully self-contained — end users don't need Python
installed. Double-clicking opens a console with the server URL and
launches their default browser at the UI.

Why a script and not just a CLI invocation: this is the canonical recipe.
Stash it in source so future builds match the current one without anyone
having to remember which flags we passed.
"""

import os
import shutil
import subprocess
import sys


REPO_ROOT = os.path.dirname(os.path.abspath(__file__))


def main():
    # Clean previous build artifacts so stale files don't sneak in.
    # On Windows, Explorer / Defender / antivirus often hold a transient
    # handle on the freshly-extracted exe (or the dist dir itself); a
    # plain rmtree fails with PermissionError mid-walk. Skip the wipe
    # if the directory is already empty (PyInstaller will overwrite
    # files cleanly inside it). For non-empty dirs, retry briefly to
    # let the AV scan finish.
    import time as _time
    for d in ('build', 'dist'):
        full = os.path.join(REPO_ROOT, d)
        if not os.path.isdir(full):
            continue
        # Try to wipe; if it fails because something's locked, only
        # complain when there's actually data left behind.
        for attempt in range(3):
            try:
                shutil.rmtree(full)
                break
            except (PermissionError, OSError):
                _time.sleep(0.5)
        else:
            # Last attempt: walk and remove individual files. If the
            # directory is empty after this, PyInstaller is happy.
            try:
                for root, dirs, files in os.walk(full, topdown=False):
                    for name in files:
                        try:
                            os.unlink(os.path.join(root, name))
                        except OSError:
                            pass
            except OSError:
                pass

    cmd = [
        sys.executable, '-m', 'PyInstaller',
        '--onefile',                       # single self-contained .exe
        '--console',                       # show URL + Ctrl-C; no GUI yet
        '--name', 'flurry',
        '--noconfirm',
        '--distpath', os.path.join(REPO_ROOT, 'dist'),
        '--workpath', os.path.join(REPO_ROOT, 'build'),
        '--specpath', os.path.join(REPO_ROOT, 'build'),
        # Ship the front-end static assets (HTML linked to /static/app.js
        # + /static/styles.css) inside the bundle. PyInstaller's --onefile
        # bootloader extracts these to sys._MEIPASS at startup; the server
        # uses importlib.resources.files('flurry') / 'static' to resolve
        # them, which works the same in source-tree and frozen modes.
        # `os.pathsep` is `;` on Windows / `:` elsewhere — PyInstaller's
        # --add-data syntax is `<src><sep><dest_in_bundle>`.
        '--add-data',
        f'{os.path.join(REPO_ROOT, "flurry", "static")}{os.pathsep}flurry/static',
        # Entry point is a tiny launcher that imports flurry as a package
        # and calls its main(). Bundling flurry/__main__.py directly would
        # turn it into a top-level script and break its relative imports.
        os.path.join(REPO_ROOT, '_pyinstaller_entry.py'),
    ]

    # Bake the multi-resolution Flurry icon into the .exe when the file
    # exists. Generated by make_icon.py; committed to the repo so users
    # cloning the source build a properly-branded binary without needing
    # Pillow installed.
    #
    # Two paths for the same icon: --icon embeds it as a Windows resource
    # so Explorer shows it on the file, and --add-data ships it as a
    # bundled file so the runtime launcher can apply it to the console
    # window via WM_SETICON (Explorer's resource doesn't propagate to
    # conhost.exe / Windows Terminal automatically).
    icon_path = os.path.join(REPO_ROOT, 'icon.ico')
    if os.path.isfile(icon_path):
        cmd.insert(-1, '--icon')
        cmd.insert(-1, icon_path)
        cmd.insert(-1, '--add-data')
        cmd.insert(-1, f'{icon_path}{os.pathsep}.')

    print('+ ' + ' '.join(cmd))
    subprocess.check_call(cmd, cwd=REPO_ROOT)

    exe_name = 'flurry.exe' if sys.platform == 'win32' else 'flurry'
    artifact = os.path.join(REPO_ROOT, 'dist', exe_name)
    print()
    print(f'Built: {artifact}')
    if os.path.exists(artifact):
        size_mb = os.path.getsize(artifact) / (1024 * 1024)
        print(f'Size:  {size_mb:.1f} MB')


if __name__ == '__main__':
    main()
